name: Build Resume and Publish to Github Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install pandoc
          curl -L https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-2/wkhtmltox-0.12.6-2.macos-cocoa.pkg -O
          sudo installer -pkg wkhtmltox-0.12.6-2.macos-cocoa.pkg -target ~

      - name: Build
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: output
          path: output

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: "output"
          single-commit: true
